//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcokul.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogretmen
    {
        public int ogretid { get; set; }
        public string ogretmenadi { get; set; }
        public string ogretmensoyadi { get; set; }
        public Nullable<int> bolumid { get; set; }
        public string emekli { get; set; }
    }
}
